version: '3.8'

# Common environment variable definitions
x-common-database: &common-database
  POSTGRES_HOST: postgres.koji.box
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB:-koji}
  POSTGRES_USER: ${POSTGRES_USER:-koji}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-koji_password}

x-common-kerberos: &common-kerberos
  KRB5_REALM: ${KRB5_REALM:-KOJI.BOX}
  KRB5_KDC: kdc.koji.box
  KRB5_ADMIN_SERVER: kdc.koji.box

x-common-koji: &common-koji
  KOJI_HUB_URL: ${KOJI_HUB_URL:-http://koji.box/kojihub}
  KOJI_WEB_URL: ${KOJI_WEB_URL:-http://koji.box/}
  KOJI_TOP_URL: ${KOJI_TOP_URL:-http://koji.box/kojifiles}
  KOJI_TOP_DIR: ${KOJI_TOP_DIR:-/mnt/koji}
  KOJI_SRC_DIR: ${KOJI_SRC_DIR:-/mnt/koji-src}

x-common-keytab-service: &common-keytab-service
  KEYTAB_SERVICE_URL: ${KEYTAB_SERVICE_URL:-http://keytabs.koji.box:5000}

x-common-orch-service: &common-orch-service
  ORCH_SERVICE_URL: ${ORCH_SERVICE_URL:-http://orch.koji.box:5000}

x-common-kadmin: &common-kadmin
  KADMIN_PRINC: ${KADMIN_PRINC:-admin/admin}
  KADMIN_PASS: ${KADMIN_PASS:-admin_password}

x-common-koji-admin: &common-koji-admin
  KOJI_ADMIN_NAME: ${KOJI_ADMIN_NAME:-hub-admin}
  KOJI_ADMIN_PRINC: ${KOJI_ADMIN_PRINC:-hub-admin@KOJI.BOX}

x-common-koji-hub: &common-koji-hub-principals
  KOJI_HUB_PRINC: ${KOJI_HUB_PRINC:-HTTP/koji-hub.koji.box@KOJI.BOX}
  KOJI_NGINX_PRINC: ${KOJI_NGINX_PRINC:-HTTP/koji.box@KOJI.BOX}
  ORCH_PRINC: ${ORCH_PRINC:-orch@KOJI.BOX}
  KOJI_CLIENT_PRINC: ${KOJI_CLIENT_PRINC:-friend@KOJI.BOX}
  KOJI_CLIENT_ADMIN_PRINC: ${KOJI_CLIENT_ADMIN_PRINC:-superfriend@KOJI.BOX}

x-common-koji-hub-keytabs: &orch-koji-hub-keytabs
  KOJI_HUB_KEYTAB: ${KOJI_HUB_KEYTAB:-789490a1-e160-49c2-a1f0-e6db926c054e}
  KOJI_HUB_PRINC: ${KOJI_HUB_PRINC:-HTTP/koji-hub.koji.box@KOJI.BOX}
  KOJI_NGINX_KEYTAB: ${KOJI_NGINX_KEYTAB:-508af9c8-01fd-413a-9865-eeaacca57c7d}
  KOJI_NGINX_PRINC: ${KOJI_NGINX_PRINC:-HTTP/koji.box@KOJI.BOX}
  KOJI_ADMIN_KEYTAB: ${KOJI_ADMIN_KEYTAB:-457de48a-d14c-4413-9eb5-c907af03f56e}
  KOJI_ADMIN_PRINC: ${KOJI_ADMIN_PRINC:-hub-admin@KOJI.BOX}

x-common-koji-web-keytab: &orch-koji-web-keytab
  KOJI_WEB_KEYTAB: ${KOJI_WEB_KEYTAB:-4a8b8ab2-e4ae-40cf-8406-08d539bc338e}
  KOJI_WEB_PRINC: ${KOJI_WEB_PRINC:-HTTP/koji-web.koji.box@KOJI.BOX}

x-common-koji-client-keytabs: &orch-koji-client-keytabs
  KOJI_CLIENT_KEYTAB: ${KOJI_CLIENT_KEYTAB:-a256f75b-8529-48ee-825d-d7ab71d65355}
  KOJI_CLIENT_PRINC: ${KOJI_CLIENT_PRINC:-friend@KOJI.BOX}
  KOJI_CLIENT_ADMIN_KEYTAB: ${KOJI_CLIENT_ADMIN_KEYTAB:-897bab27-3a1b-4bc5-9ba5-8954d206330b}
  KOJI_CLIENT_ADMIN_PRINC: ${KOJI_CLIENT_ADMIN_PRINC:-superfriend@KOJI.BOX}

x-common-koji-worker-keytab: &orch-koji-worker-keytab
  KOJI_WORKER_KEYTAB: ${KOJI_WORKER_KEYTAB:-033dbe9b-d003-47eb-8383-fcc6babc2619}

x-common-koji-hub-cert: &orch-koji-hub-cert
  KOJI_HUB_CERT: ${KOJI_HUB_CERT:-28661f1e-f1a9-461f-a05c-6c399a8c66f3}
  KOJI_HUB_CERT_CN: ${KOJI_HUB_CERT_CN:-koji-hub.koji.box}
  KOJI_HUB_KEY: ${KOJI_HUB_KEY:-b5876248-dc72-498c-af2a-1b28723bee52}

x-common-koji-nginx-cert: &orch-koji-nginx-cert
  KOJI_NGINX_CERT: ${KOJI_NGINX_CERT:-482ae0cb-41d3-4a01-88fd-d86c557bc75a}
  KOJI_NGINX_CERT_CN: ${KOJI_NGINX_CERT_CN:-koji.box}
  KOJI_NGINX_KEY: ${KOJI_NGINX_KEY:-c016e63d-d250-4b57-af1e-2f35fd5b51fe}


services:
  postgres:
    image: postgres:15-alpine
    container_name: koji-boxed-postgres
    environment:
      <<: [*common-database,
           *common-koji-admin]
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./services/postgres/init.d:/docker-entrypoint-initdb.d:Z
      - ./koji-src/:/mnt/koji-src:Z
    expose:
      - "5432"
    networks:
      koji-network:
        aliases:
          - postgres.koji.box
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-koji} -d ${POSTGRES_DB:-koji}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEMORY_LIMIT:-1g}
        reservations:
          memory: 512m

  kdc:
    build:
      context: .
      dockerfile: services/kdc/Dockerfile
    container_name: koji-boxed-kdc
    environment:
      <<: [*common-kerberos,
           *common-kadmin]
    volumes:
      - kdc_data:/var/lib/krb5kdc:Z
      - ./services/kdc/init.d:/var/lib/krb5kdc/kdc-init.d:Z
      - ./data/logs/kdc:/var/log/krb5kdc:Z
    expose:
      - "88"
      - "749"
      - "464"
    networks:
      koji-network:
        aliases:
          - kdc.koji.box
    healthcheck:
      test: ["CMD-SHELL", "/bin/health-check.sh"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

  orch-service:
    build:
      context: .
      dockerfile: services/orch/Dockerfile
    container_name: koji-boxed-orch-service
    depends_on:
      kdc:
        condition: service_healthy
    privileged: true
    environment:
      <<: [*common-kerberos,
           *common-koji,
           *common-kadmin,
           *common-orch-service,
           *orch-koji-hub-keytabs,
           *orch-koji-web-keytab,
           *orch-koji-client-keytabs,
           *orch-koji-worker-keytab,
           *orch-koji-hub-cert,
           *orch-koji-nginx-cert]
      ORCH_PRINC: ${ORCH_PRINC:-orch@KOJI.BOX}
      ORCH_KEYTAB: ${ORCH_KEYTAB:-4e344539-8902-4ea1-8797-cd49de9e1c5f}
    volumes:
      # see SOCKET_README.md for details on using PODMAN_SOCKET with rootless podman
      - ${PODMAN_SOCKET:-/var/run/podman.sock}:/var/run/docker.sock
      - orch_data:/mnt/data:Z
      - ./services/orch/templates/resource_mapping.yaml.template:/app/resource_mapping.yaml.template:ro,Z
    networks:
      koji-network:
        aliases:
          - orch.koji.box
    healthcheck:
      test: ["CMD-SHELL", "/app/orch.sh health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  koji-hub:
    build:
      context: .
      dockerfile: services/koji-hub/Dockerfile
    container_name: koji-boxed-koji-hub
    hostname: koji-hub.koji.box
    depends_on:
      postgres:
        condition: service_healthy
      orch-service:
        condition: service_healthy
    environment:
      <<: [*common-database,
           *common-koji,
           *common-kerberos,
           *common-orch-service,
           *common-koji-hub-principals,
           *orch-koji-hub-keytabs,
           *orch-koji-hub-cert]
      KOJI_HUB_URL: https://koji-hub.koji.box/kojihub  # override to bypass nginx

    volumes:
      - koji_storage:/mnt/koji:Z
      - ./services/koji-hub/init.d:/var/lib/koji-hub/hub-init.d:Z
      - ./data/logs/hub:/var/log/koji-hub:Z
    expose:
      - "80"
      - "443"
    networks:
      koji-network:
        aliases:
          - koji-hub.koji.box
    healthcheck:
      test: ["CMD-SHELL", "koji version || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: ${HUB_MEMORY_LIMIT:-512m}
        reservations:
          memory: 256m

  koji-worker:
    build:
      context: .
      dockerfile: services/koji-worker/Dockerfile
    container_name: koji-boxed-koji-worker
    hostname: koji-worker-1.koji.box
    depends_on:
      koji-hub:
        condition: service_healthy
      orch-service:
        condition: service_healthy
    environment:
      <<: [*common-orch-service,
           *common-koji,
           *common-kerberos]
    volumes:
      - koji_storage:/mnt/koji
      - ./data/logs/worker:/var/log/koji-worker
    networks:
      koji-network:
        aliases:
          - koji-worker-1.koji.box
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep koji-worker || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEMORY_LIMIT:-1g}
        reservations:
          memory: 512m
    profiles:
      - "workers"

  koji-web:
    build:
      context: .
      dockerfile: services/koji-web/Dockerfile
    container_name: koji-boxed-koji-web
    depends_on:
      koji-hub:
        condition: service_healthy
      orch-service:
        condition: service_healthy
    environment:
      <<: [*common-koji,
           *common-kerberos,
           *common-orch-service]
    volumes:
      - ./services/koji-web:/etc/koji-web:Z
    expose:
      - "8080"
    networks:
      koji-network:
        aliases:
          - koji-web.koji.box
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: ${WEB_MEMORY_LIMIT:-256m}
        reservations:
          memory: 128m
    profiles:
      - "web"

  koji-client:
    build:
      context: .
      dockerfile: services/koji-client/Dockerfile
    container_name: koji-boxed-koji-client
    depends_on:
      orch-service:
        condition: service_healthy
      nginx:
        condition: service_healthy
      koji-hub:
        condition: service_healthy
    environment:
      <<: [*common-kerberos,
           *common-koji,
           *common-orch-service,
           *orch-koji-client-keytabs]
    volumes:
      - koji_storage:/mnt/koji:ro
      - ./services/koji-client/init.d:/var/lib/koji-client/client-init.d:Z
    networks:
      koji-network:
        aliases:
          - koji-client.koji.box
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
    profiles:
      - "shell"

  nginx:
    image: nginx:alpine
    container_name: koji-boxed-nginx
    depends_on:
      # koji-web:
      #  condition: service_healthy
      koji-hub:
        condition: service_healthy
    volumes:
      - koji_storage:/mnt/koji:ro
      - ./services/nginx:/etc/nginx:Z
      - ./data/logs/nginx:/var/log/nginx:Z
    ports:
      - "8080:80"
      - "8443:443"
    expose:
      - "80"
      - "443"
    networks:
      koji-network:
        aliases:
          - koji.box
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m


networks:
  koji-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${KOJI_SUBNET:-172.20.0.0/16}


volumes:
  postgres_data:
    driver: local
  koji_storage:
    driver: local
  kdc_data:
    driver: local
  orch_data:
    driver: local


# The end.
