---
# Example Koji Hosts Configuration
#
# This file defines build hosts that will be registered in your Koji instance.
# Each host can build for specific architectures and has a capacity setting.
#
# Common architectures:
# - x86_64: 64-bit Intel/AMD
# - i686: 32-bit Intel/AMD
# - noarch: Architecture independent packages
# - aarch64: 64-bit ARM
# - ppc64le: 64-bit PowerPC Little Endian
# - s390x: IBM System z

- name: "builder01.koji.box"
  arches:
    - "x86_64"
    - "noarch"
  capacity: 10.0
  enabled: true
  state: "present"

- name: "builder02.koji.box"
  arches:
    - "x86_64"
    - "i686"
    - "noarch"
  capacity: 5.0
  enabled: true
  state: "present"

- name: "arm-builder01.koji.box"
  arches:
    - "aarch64"
    - "noarch"
  capacity: 3.0
  enabled: true
  state: "present"

# Example of a disabled host
- name: "maintenance-builder.koji.box"
  arches:
    - "x86_64"
    - "noarch"
  capacity: 1.0
  enabled: false
  state: "present"

# Example of removing a host
# - name: "old-builder.koji.box"
#   state: "absent"
