---
- name: Configure Koji Instance
  hosts: koji-hub
  gather_facts: false
  vars:
    # Load configuration from separate files
    koji_users: "{{ lookup('file', 'users.yml') | from_yaml | default([]) }}"
    koji_hosts: "{{ lookup('file', 'hosts.yml') | from_yaml | default([]) }}"
    koji_tags: "{{ lookup('file', 'tags.yml') | from_yaml | default([]) }}"
    koji_targets: "{{ lookup('file', 'targets.yml') | from_yaml | default([]) }}"

  tasks:
    - name: Verify koji connection
      shell: koji --noauth version
      register: koji_version
      changed_when: false

    - name: Display koji version
      debug:
        msg: "Configuring Koji version: {{ koji_version.stdout }}"

    - name: Configure Koji users
      koji_user:
        name: "{{ item.name }}"
        principal: "{{ item.principal }}"
        permissions: "{{ item.permissions | default([]) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ koji_users }}"
      when: koji_users | length > 0

    - name: Configure Koji hosts
      koji_host:
        name: "{{ item.name }}"
        arches: "{{ item.arches | default(['x86_64', 'noarch']) }}"
        capacity: "{{ item.capacity | default(1.0) }}"
        enabled: "{{ item.enabled | default(true) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ koji_hosts }}"
      when: koji_hosts | length > 0

    - name: Configure Koji tags
      shell: |
        # Check if tag exists
        if ! koji --noauth call --json-output getTag "{{ item.name }}" >/dev/null 2>&1; then
          # Tag doesn't exist, create it
          koji add-tag "{{ item.name }}" \
            {% if item.parent is defined and item.parent %} --parent="{{ item.parent }}"{% endif %} \
            {% if item.locked | default(false) %} --locked{% endif %} \
            {% if item.maven_support | default(false) %} --maven-support{% endif %}
          echo "created"
        else
          echo "exists"
        fi
      register: tag_result
      changed_when: tag_result.stdout.strip() == "created"
      loop: "{{ koji_tags }}"
      when: koji_tags | length > 0

    - name: Configure Koji targets
      shell: |
        # Check if target exists
        if ! koji --noauth call --json-output getBuildTarget "{{ item.name }}" >/dev/null 2>&1; then
          # Target doesn't exist, create it
          koji add-target "{{ item.name }}" "{{ item.build_tag }}" "{{ item.dest_tag }}"
          echo "created"
        else
          echo "exists"
        fi
      register: target_result
      changed_when: target_result.stdout.strip() == "created"
      loop: "{{ koji_targets }}"
      when: koji_targets | length > 0

    - name: Configuration summary
      debug:
        msg: |
          Koji configuration completed:
          - Users: {{ koji_users | length }}
          - Hosts: {{ koji_hosts | length }}
          - Tags: {{ koji_tags | length }}
          - Targets: {{ koji_targets | length }}
